mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mappers/*.xml
spring.sql.init.mode: always

spring:
  datasource:
    url: jdbc:h2:mem:region-catalog
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true